version: "3"

services:
  db:
    image: postgres:11
    environment:
      POSTGRES_USER: test_production
      POSTGRES_DB: test_production
      POSTGRES_PASSWORD: Test123
    container_name: test-db-1
    volumes:
      - "./db:/var/lib/postgresql/data"
    networks:
      - internal

  av:
    image: feduxorg/clamav
    container_name: test-av-1
    networks:
      - internal

  web:
    image: feduxorg/www_test_server
    container_name: test-web-1
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:test.example.com
    environment:
      DATABASE_URL: postgresql://test_production:Test123@test-db-1:5432/test_production
      RAILS_MAX_THREADS: 5
      CLAMAV_CLAMD_TCP_ADDRESS: test-av-1
      # RAILS_ENV: development
      # LOG_LEVEL: debug
    ports:
      - 3000:3000
    volumes:
      - ./src:/srv/app
    networks:
      - internal
    depends_on:
      - db

networks:
  internal:
    external:
      name: internal
