source 'https://rubygems.org'

# Authentication and Authorization
gem 'pundit'
gem 'devise'

# Environment Variables as configuration
gem 'dotenv-rails'
gem 'dotenv'

# File handling
gem 'refile', require: 'refile/rails', git: 'https://github.com/refile/refile.git'

# Whois
gem 'whois'
gem 'kramdown'

# Helpers
gem 'activesupport'
gem 'addressable'
gem 'bcrypt', '~> 3.1.7'

# Layout
gem 'bootstrap', '~> 5.1.0'
gem 'sass-rails', '>=2.1.0'
gem 'font-awesome-sass', '~> 5.15'

gem 'breadcrumbs_on_rails'
# gem 'coffee-rails', '~> 4.0.0'
gem 'haml', '~>5.0'
gem 'haml-rails'
gem 'i18n'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
# gem 'pager'
gem 'puma', '~> 5.6'
# gem 'rack-contrib'
gem 'rack-cors', require: 'rack/cors'
gem 'rails', '~>5.2.0'
gem 'rails-i18n'
gem 'ruby-filemagic'
gem 'sprockets-rails'
gem 'autoprefixer-rails'

# Database
gem 'sqlite3', '~> 1.4.2'
gem 'pg'
# disabled because not used
# gem 'mysql2'

gem 'mini_racer'
gem 'thor'
# gem 'turbolinks'
gem 'uglifier', '>= 1.3.0'

group :development do
  gem 'foreman', require: false
  gem 'github-markup'
  gem 'redcarpet', require: false
  gem 'tmrb', require: false
  gem 'yard', require: false
  gem 'inch', require: false
  gem 'spring'
end

group :profile do
  gem 'ruby-prof'
end

group :development, :test do
  gem 'aruba', require: false
  gem 'capybara', require: false
  gem 'coveralls', require: false
  gem 'cucumber', require: false

  # gem 'pry-byebug', require: false
  # gem 'byebug'

  gem 'erubi'
  gem 'excon'
  gem 'fuubar', require: false
  gem 'launchy'
  gem 'nokogiri'
  gem 'poltergeist', require: 'capybara/poltergeist'

  gem 'pry-rails'
  gem 'pry', require: false
  gem 'pry-doc', require: false

  gem 'rack-test', require: 'rack/test'
  gem 'rake', require: false
  gem 'rspec', require: false
  gem 'rspec-rails', '~> 3.9'
  gem 'rubocop', require: false
  gem 'shotgun'
  gem 'simplecov', require: false
  gem 'versionomy', require: false
  gem 'awesome_print', require: 'ap'
  # gem 'sinatra', require: 'sinatra/base'
  gem 'filegen'

  gem 'better_errors'
  gem 'binding_of_caller'
end
